# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  release:
    types: [published]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    strategy:
      matrix:
        go-version: [1.24.4]
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: |
       go build -o gollama-chat-${{ matrix.goos }}-${{ matrix.goarch }}-${{ github.event.release.tag_name }} cmd/main.go

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: gollama-chat-${{ matrix.goos }}-${{ matrix.goarch }}-${{ github.event.release.tag_name }}
        asset_name: gollama-chat-${{ matrix.goos }}-${{ matrix.goarch }}-${{ github.event.release.tag_name }}
        asset_content_type: application/octet-stream
